#!/usr/bin/env ruby

require File.expand_path('../../config/environment', __FILE__)
require 'vidibus/watch_folder/daemon'

Vidibus::WatchFolder.autoload_paths << Rails.root.join('app/**/*.rb')
Vidibus::WatchFolder.path_mapping << [Rails.root.to_s, '.+']
Vidibus::WatchFolder::Daemon.new(ARGV).daemonize
